<a href="https://colab.research.google.com/github/ash0987/Resume/blob/master/Mini_Project_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from skimage.io import imread
from skimage.transform import resize
import matplotlib.pyplot as plt
import os
from skimage.color import rgb2gray 
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from xgboost import XGBClassifier

In [2]:
cat= {'a':0,'b':1,'m':2,'o':3}

In [3]:
def getData(s):
  path = os.path.join('/content/drive/MyDrive/mini project/',s)
  x=[]
  y=[]
  for i in os.listdir(path):
    img = imread(os.path.join(path,i))
    img = resize(img,(100,100,3))
    img = rgb2gray(img)
    flatten_img = np.ndarray.flatten(img)
    x.append(flatten_img)
    y.append(cat[i[0]])
  data=np.array(x)
  target=np.array(y)
  return data, target

In [4]:
x_train,y_train = getData('train')
x_test,y_test = getData('test')

In [5]:
np.unique(y_train,return_counts=True)

(array([0, 1, 2, 3]), array([75, 73, 20, 72]))

In [6]:
np.unique(y_test,return_counts=True)

(array([0, 1, 2, 3]), array([19, 18,  5, 18]))

In [7]:
#Using SVM

In [8]:
gamma=[1,0.01,0.001,0.0001]
C=[0.1,1,10,100]

In [9]:
# Checking with SVM

In [10]:
param_grid = { 'gamma':gamma,'C':C, 'kernel':['rbf','linear','poly']}
svc = svm.SVC()
clf = GridSearchCV(svc, param_grid)
clf.fit(x_train, y_train)

clf.best_params_

{'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}

In [11]:
y_pred=clf.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.89      0.83        19
           1       0.68      0.72      0.70        18
           2       1.00      0.20      0.33         5
           3       0.67      0.67      0.67        18

    accuracy                           0.72        60
   macro avg       0.78      0.62      0.63        60
weighted avg       0.73      0.72      0.70        60

[[17  1  0  1]
 [ 2 13  0  3]
 [ 1  1  1  2]
 [ 2  4  0 12]]


In [12]:
# Checking with XGBClassifier

In [15]:
param_grid = {
    'colsample_bytree': [0.7, 0.8],
    'max_depth': [10,15]
}

In [16]:
model = XGBClassifier()
clf = GridSearchCV(model, param_grid)
clf.fit(x_train, y_train)

clf.best_params_

{'colsample_bytree': 0.7, 'max_depth': 10}

In [17]:
y_pred=clf.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.95      0.86        19
           1       0.81      0.72      0.76        18
           2       0.00      0.00      0.00         5
           3       0.67      0.78      0.72        18

    accuracy                           0.75        60
   macro avg       0.57      0.61      0.58        60
weighted avg       0.69      0.75      0.72        60

[[18  0  0  1]
 [ 1 13  0  4]
 [ 2  1  0  2]
 [ 2  2  0 14]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
